import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT = path.resolve(__dirname, '..');
const PUBLIC_IMAGES = path.join(ROOT, 'public', 'images');
const OUTPUT = path.join(ROOT, 'src', 'data', 'imageAssets.js');

const CATEGORY_ORDER = [
  'fichas',
  'balones',
  'chinos',
  'muñecos',
  'picas',
  'porterías',
  'escaleras y aros',
  'vista',
  'varios',
];

const CATEGORY_LABELS = {
  'fichas': 'Fichas',
  'balones': 'Balones',
  'chinos': 'Chinos',
  'muñecos': 'Muñecos',
  'picas': 'Picas',
  'porterías': 'Porterías',
  'escaleras y aros': 'Escaleras y Aros',
  'vista': 'Vista',
  'varios': 'Varios',
};

function scanFolder(folderPath) {
  if (!fs.existsSync(folderPath)) return [];
  return fs.readdirSync(folderPath)
    .filter(f => f.endsWith('.webp'))
    .sort();
}

function scanObjectsRecursively(basePath) {
  if (!fs.existsSync(basePath)) return {};
  const result = {};
  const entries = fs.readdirSync(basePath, { withFileTypes: true });

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const folderPath = path.join(basePath, entry.name);
      const files = scanFolder(folderPath);
      if (files.length > 0) {
        const categoryName = entry.name;
        const categoryPath = `images/templates/objects/${categoryName}`;
        result[categoryName] = files.map(f => ({
          id: f.replace('.webp', ''),
          src: `${categoryPath}/${f}`,
          name: f.replace('.webp', '').replace(/-/g, ' '),
        }));
      }
    }
  }
  return result;
}

function generate() {
  const fields = scanFolder(path.join(PUBLIC_IMAGES, 'templates', 'fields'));

  const fieldsData = fields.map((f, i) => ({
    id: `field${i + 1}`,
    src: `images/templates/fields/${f}`,
    name: `Campo ${i + 1}`,
  }));

  const objectsByCategoryRaw = scanObjectsRecursively(path.join(PUBLIC_IMAGES, 'templates', 'objects'));

  // Build ordered array with explicit labels
  const objectsByCategory = CATEGORY_ORDER
    .filter(key => objectsByCategoryRaw[key])
    .map(key => ({
      key,
      label: CATEGORY_LABELS[key] || key,
      items: objectsByCategoryRaw[key],
    }));

  // Flat array for backward compatibility
  const allObjects = Object.values(objectsByCategoryRaw).flat();

  const content = `// Auto-generated by scripts/generate-assets.js
// Do not edit manually. Add images to public/images/templates/ and re-run.

export const FIELDS = ${JSON.stringify(fieldsData, null, 2)};

export const OBJECTS_BY_CATEGORY = ${JSON.stringify(objectsByCategory, null, 2)};

// Flat array for backward compatibility
export const OBJECTS = ${JSON.stringify(allObjects, null, 2)};
`;

  const outputDir = path.dirname(OUTPUT);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT, content);

  console.log(`Generated ${OUTPUT}`);
  console.log(`  Fields: ${fieldsData.length}`);
  console.log(`  Categories: ${objectsByCategory.length}`);
  for (const cat of objectsByCategory) {
    console.log(`    - ${cat.label}: ${cat.items.length} objects`);
  }
  console.log(`  Total objects: ${allObjects.length}`);
}

generate();
