import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT = path.resolve(__dirname, '..');
const PUBLIC_IMAGES = path.join(ROOT, 'public', 'images');
const OUTPUT = path.join(ROOT, 'src', 'data', 'imageAssets.js');

function scanFolder(folderPath) {
  if (!fs.existsSync(folderPath)) return [];
  return fs.readdirSync(folderPath)
    .filter(f => f.endsWith('.webp'))
    .sort();
}

function generate() {
  const fields = scanFolder(path.join(PUBLIC_IMAGES, 'templates', 'fields'));
  const objects = scanFolder(path.join(PUBLIC_IMAGES, 'templates', 'objects', 'extracted'));

  const fieldsData = fields.map((f, i) => ({
    id: `field${i + 1}`,
    src: `images/templates/fields/${f}`,
    name: `Campo ${i + 1}`,
  }));

  const objectsData = objects.map(f => ({
    id: f.replace('.webp', ''),
    src: `images/templates/objects/extracted/${f}`,
    name: f.replace('.webp', ''),
  }));

  const content = `// Auto-generated by scripts/generate-assets.js
// Do not edit manually. Add images to public/images/templates/ and re-run.

export const FIELDS = ${JSON.stringify(fieldsData, null, 2)};

export const OBJECTS = ${JSON.stringify(objectsData, null, 2)};
`;

  const outputDir = path.dirname(OUTPUT);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT, content);

  console.log(`Generated ${OUTPUT}`);
  console.log(`  Fields: ${fieldsData.length}`);
  console.log(`  Objects: ${objectsData.length}`);
}

generate();
