/**
 * Resolve the Firestore doc id used when mirroring a local Dexie write.
 *
 * For autoincrement (++id) tables, Dexie invokes the `creating` hook with a
 * null primKey: the real key is only generated by IndexedDB after the hook.
 * Returning a value from the hook makes Dexie use it as the generated key
 * (and persist it back into obj.id), so every new row gets a stable id and
 * Firestore docs stop colliding on ".../null".
 */
export function resolveSyncKey(primKey, obj) {
  if (primKey != null) {
    return { key: primKey, assignToObj: false };
  }

  if (obj && obj.id != null) {
    return { key: obj.id, assignToObj: false };
  }

  const key = generateStableKey();
  return { key, assignToObj: true };
}

function generateStableKey() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return `${Date.now()}-${Math.random().toString(36).slice(2)}`;
}
