name: Release App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Permite compilar manualmente desde la pestaña Actions

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    defaults:
      run:
        working-directory: gkapp-web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: gkapp-web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Vite
        run: npm run build

      - name: Build and Publish Electron
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || 'mac' }} --publish always