import { useState, useRef, useEffect, useCallback } from 'react';
import { Square, Circle, ArrowRight, Type, Trash2, RotateCw, ChevronUp, ChevronDown, ChevronRight, RotateCcw, Paintbrush, LayoutTemplate, AlignLeft, AlignCenter, AlignRight, AlignCenterVertical, AlignCenterHorizontal, AlignHorizontalDistributeCenter, AlignVerticalDistributeCenter, Triangle, Hash, Link, Clipboard, Plus, Save, Star, Undo2, Redo2 } from 'lucide-react';
import { FIELDS, OBJECTS_BY_CATEGORY } from '../data/imageAssets.js';
import { getSetting, setSetting } from '../db.js';

function uid() { return Math.random().toString(36).substr(2, 9); }

function normalize(str) {
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
}

function getArrowBox(el) {
  const minX = Math.min(el.x1, el.x2);
  const minY = Math.min(el.y1, el.y2);
  const maxX = Math.max(el.x1, el.x2);
  const maxY = Math.max(el.y1, el.y2);
  return { x: minX, y: minY, w: Math.max(10, maxX - minX), h: Math.max(10, maxY - minY) };
}

function normalizeRotation(rot) {
  while (rot > 180) rot -= 360;
  while (rot <= -180) rot += 360;
  return rot;
}

export default function ImageEditor({ onSave, onCancel, taskData = {}, initialElements = null, corporateColor = '#dc2626', autoRepair = false }) {
  const canvasRef = useRef(null);
  const [canvasSize, setCanvasSize] = useState({ w: 800, h: 600 });
  const [elements, setElements] = useState(initialElements || []);
  const [selectedIds, setSelectedIds] = useState([]);
  const [toolTab, setToolTab] = useState('fields');
  const [dragging, setDragging] = useState(null); // eslint-disable-line no-unused-vars
  const [resizing, setResizing] = useState(null); // eslint-disable-line no-unused-vars
  const [rotating, setRotating] = useState(null); // eslint-disable-line no-unused-vars
  const [editingTextId, setEditingTextId] = useState(null);
  const [clipboard, setClipboard] = useState(null);
  const [pasteCount, setPasteCount] = useState(0);
  const [selectBox, setSelectBox] = useState(null);
  const [canUndo, setCanUndo] = useState(false);
  const [canRedo, setCanRedo] = useState(false);

  const selectBoxRef = useRef(null);
  const draggingRef = useRef(null);
  const resizingRef = useRef(null);
  const rotatingRef = useRef(null);
  const elementsRef = useRef(elements);
  const canvasSizeRef = useRef(canvasSize);
  const historyRef = useRef({ past: [], future: [] });
  const pushHistoryRef = useRef(null);
  const autoGeneratedRef = useRef(false);
  const autoRepairTriggeredRef = useRef(false);

  const pushHistory = useCallback(() => {
    historyRef.current = { past: [...historyRef.current.past, JSON.parse(JSON.stringify(elements))], future: [] };
    setCanUndo(true);
    setCanRedo(false);
  }, [elements]);
  useEffect(() => { pushHistoryRef.current = pushHistory; }, [pushHistory]);

  const undo = useCallback(() => {
    const { past, future } = historyRef.current;
    if (past.length === 0) return;
    const prev = past[past.length - 1];
    historyRef.current = { past: past.slice(0, -1), future: [JSON.parse(JSON.stringify(elements)), ...future] };
    setElements(prev);
    setSelectedIds([]);
    setCanUndo(historyRef.current.past.length > 0);
    setCanRedo(true);
  }, [elements]);

  const redo = useCallback(() => {
    const { past, future } = historyRef.current;
    if (future.length === 0) return;
    const next = future[0];
    historyRef.current = { past: [...past, JSON.parse(JSON.stringify(elements))], future: future.slice(1) };
    setElements(next);
    setSelectedIds([]);
    setCanUndo(true);
    setCanRedo(historyRef.current.future.length > 0);
  }, [elements]);

  useEffect(() => { elementsRef.current = elements; }, [elements]);
  useEffect(() => { canvasSizeRef.current = canvasSize; }, [canvasSize]);
  const fileInputRef = useRef();
  const objectFileInputRef = useRef();
  const [showAddObjectModal, setShowAddObjectModal] = useState(false);
  const [objectUrl, setObjectUrl] = useState('');
  const [showTextInputModal, setShowTextInputModal] = useState(false);
  const [textInputValue, setTextInputValue] = useState('');
  const [objectSearch, setObjectSearch] = useState('');
  const [expandedCategories, setExpandedCategories] = useState(() => new Set());
  const [shapePresets, setShapePresets] = useState({ rect: [], circle: [], triangle: [], arrow: [] });

  useEffect(() => {
    (async () => {
      const saved = await getSetting('drawingPresets');
      if (saved) {
        setShapePresets(saved);
      } else {
        try {
          const local = JSON.parse(localStorage.getItem('shapePresets'));
          if (local) {
            setShapePresets(local);
            await setSetting('drawingPresets', local);
            localStorage.removeItem('shapePresets');
          }
        } catch { /* ignore */ }
      }
    })();
  }, []);
  const [showPresetName, setShowPresetName] = useState(false);
  const [presetName, setPresetName] = useState('');

  useEffect(() => {
    const fieldEl = elements.find(e => e.type === 'field');
    const fieldSrc = fieldEl?.src;
    if (!fieldSrc) return;
    const img = new Image();
    img.onload = () => {
      const maxW = Math.min(window.innerWidth - 420, 1000);
      const scale = Math.min(1, maxW / img.naturalWidth);
      const newW = img.naturalWidth * scale;
      const newH = img.naturalHeight * scale;
      setCanvasSize({ w: newW, h: newH });
      setElements(prev => prev.map(el =>
        el.type === 'field' ? { ...el, w: newW, h: newH } : el
      ));
      if (!initialElements && !autoGeneratedRef.current) {
        const hasContent = taskData.subtitle || taskData.focus || taskData.description || taskData.time || taskData.reps;
        if (hasContent) {
          autoGeneratedRef.current = true;
          autoGenerateCard(newW, newH);
        }
      }
      if (autoRepair && !autoRepairTriggeredRef.current) {
        autoRepairTriggeredRef.current = true;
        setTimeout(() => capture(), 500);
      }
    };
    img.src = fieldSrc;
  }, [elements]);

  const addElement = useCallback((type, extra = {}) => {
    pushHistory();
    const id = uid();
    if (type === 'field') {
      setElements(prev => {
        const filtered = prev.filter(e => e.type !== 'field');
        return [...filtered, { id, type, x: 0, y: 0, w: canvasSize.w, h: canvasSize.h, zIndex: 0, ...extra }];
      });
    } else if (type === 'text') {
      setElements(prev => [...prev, {
        id, type, x: canvasSize.w / 2 - 50, y: canvasSize.h / 2 - 25, w: 200, h: 40,
        text: extra.text || 'Texto', fontSize: extra.fontSize || 20, color: extra.color || '#000000',
        fontWeight: extra.fontWeight || 'normal', bgColor: extra.bgColor || 'transparent',
        textAlign: extra.textAlign || 'left', padding: extra.padding || 4,
        stroke: extra.stroke || '#000000', strokeWidth: extra.strokeWidth || 2, noStroke: true,
        rotation: 0, opacity: 1, flipH: false, zIndex: prev.length + 1,
      }]);
    } else if (type === 'rect') {
      setElements(prev => [...prev, {
        id, type, x: canvasSize.w / 2 - 50, y: canvasSize.h / 2 - 50, w: 100, h: 100,
        fill: 'transparent', stroke: '#000000', strokeWidth: 3, fillType: 'transparent',
        strokeStyle: 'solid', fillOpacity: 0.2,
        rotation: 0, opacity: 1, flipH: false, zIndex: prev.length + 1,
      }]);
    } else if (type === 'circle') {
      setElements(prev => [...prev, {
        id, type, x: canvasSize.w / 2 - 50, y: canvasSize.h / 2 - 50, w: 100, h: 100,
        fill: 'transparent', stroke: '#000000', strokeWidth: 3, fillType: 'transparent',
        strokeStyle: 'solid', fillOpacity: 0.2,
        rotation: 0, opacity: 1, flipH: false, zIndex: prev.length + 1,
      }]);
    } else if (type === 'triangle') {
      setElements(prev => [...prev, {
        id, type, x: canvasSize.w / 2 - 50, y: canvasSize.h / 2 - 50, w: 100, h: 100,
        fill: 'transparent', stroke: '#000000', strokeWidth: 3, fillType: 'transparent',
        strokeStyle: 'solid', fillOpacity: 0.2,
        rotation: 0, opacity: 1, flipH: false, zIndex: prev.length + 1,
      }]);
    } else if (type === 'number') {
      setElements(prev => [...prev, {
        id, type, x: canvasSize.w / 2 - 30, y: canvasSize.h / 2 - 30, w: 60, h: 60,
        number: 1, numberColor: extra.numberColor || '#000000',
        fontSize: extra.fontSize || 28, fontWeight: 'bold',
        stroke: extra.stroke || '#000000', strokeWidth: extra.strokeWidth || 3,
        bgColor: extra.bgColor || '#ffffff', noStroke: false,
        rotation: 0, opacity: 1, flipH: false, zIndex: prev.length + 1,
      }]);
    } else if (type === 'arrow') {
      const x1 = canvasSize.w / 2 - 60;
      const y1 = canvasSize.h / 2;
      const x2 = canvasSize.w / 2 + 60;
      const y2 = canvasSize.h / 2;
      setElements(prev => [...prev, {
        id, type, x1, y1, x2, y2,
        stroke: '#000000', strokeWidth: 4, headStyle: 'standard',
        doubleHead: false, headSize: 4, strokeStyle: 'solid',
        opacity: 1, flipH: false, zIndex: prev.length + 1,
      }]);
    } else {
      setElements(prev => [...prev, {
        id, type, x: canvasSize.w / 2 - 50, y: canvasSize.h / 2 - 50, w: 100, h: 100,
        rotation: 0, opacity: 1, flipH: false, zIndex: prev.length + 1, ...extra,
      }]);
    }
    setSelectedIds([id]);
  }, [canvasSize.w, canvasSize.h]);

  const autoGenerateCard = (cW, cH) => {
    const { subtitle, focus, description, time, reps } = taskData;
    const pad = 60;
    const lineH = 22;
    const gap = 6;
    const badgeH = 30;
    let z = 1;
    const els = [];

    // --- Top row: CONTENIDO + FOCO side by side ---
    const topY = 10;
    const badgePadX = 8;
    const valOffset = 10;

    if (subtitle) {
      const label = 'CONTENIDO';
      const badgeW = label.length * 9 + badgePadX * 2;
      els.push({ id: uid(), type: 'text', x: pad, y: topY, w: badgeW, h: badgeH, text: label, fontSize: 13, color: corporateColor, fontWeight: 'bold', bgColor: 'transparent', stroke: corporateColor, strokeWidth: 2, textAlign: 'center', padding: 2, rotation: 0, opacity: 1, flipH: false, zIndex: z++, noStroke: false });
      els.push({ id: uid(), type: 'text', x: pad + badgeW + valOffset, y: topY, w: cW * 0.3, h: badgeH, text: String(subtitle).toUpperCase(), fontSize: 12, color: '#000000', fontWeight: 'bold', bgColor: 'transparent', textAlign: 'left', padding: 2, rotation: 0, opacity: 1, flipH: false, zIndex: z++, noStroke: true });
    }

    if (focus) {
      const label = 'FOCO';
      const badgeW = label.length * 9 + badgePadX * 2;
      const focusX = cW * 0.55;
      els.push({ id: uid(), type: 'text', x: focusX, y: topY, w: badgeW, h: badgeH, text: label, fontSize: 13, color: corporateColor, fontWeight: 'bold', bgColor: 'transparent', stroke: corporateColor, strokeWidth: 2, textAlign: 'center', padding: 2, rotation: 0, opacity: 1, flipH: false, zIndex: z++, noStroke: false });
      els.push({ id: uid(), type: 'text', x: focusX + badgeW + valOffset, y: topY, w: cW * 0.35, h: badgeH, text: String(focus).toUpperCase(), fontSize: 12, color: '#000000', fontWeight: 'bold', bgColor: 'transparent', textAlign: 'left', padding: 2, rotation: 0, opacity: 1, flipH: false, zIndex: z++, noStroke: true });
    }

    // --- Box for time + reps ---
    if (time || reps) {
      const boxX = 15;
      const boxY = topY + badgeH + gap + 8;
      const boxW = 80;
      const rowH = 32;
      const boxH = (time && reps) ? rowH * 2 : rowH;
      const midY = boxY + rowH;
      const colSplit = boxX + 36;

      // Outer border
      els.push({ id: uid(), type: 'rect', x: boxX, y: boxY, w: boxW, h: boxH, stroke: corporateColor, strokeWidth: 2, fill: 'transparent', cornerRadius: 0, rotation: 0, opacity: 1, flipH: false, zIndex: z++, noStroke: false });

      // Horizontal divider (if both time and reps)
      if (time && reps) {
        els.push({ id: uid(), type: 'arrow', x1: boxX, y1: midY, x2: boxX + boxW, y2: midY, stroke: corporateColor, strokeWidth: 1.5, headStyle: 'none', doubleHead: false, headSize: 0.5, strokeStyle: 'dashed', opacity: 1, flipH: false, zIndex: z++ });
      }

      // Vertical divider
      els.push({ id: uid(), type: 'arrow', x1: colSplit, y1: boxY, x2: colSplit, y2: boxY + boxH, stroke: corporateColor, strokeWidth: 1.5, headStyle: 'none', doubleHead: false, headSize: 0.5, strokeStyle: 'dashed', opacity: 1, flipH: false, zIndex: z++ });

      // Time row
      if (time) {
        const tRowY = boxY + (rowH - lineH) / 2;
        els.push({ id: uid(), type: 'text', x: boxX + 2, y: tRowY, w: 32, h: lineH, text: '\u23F1', fontSize: 15, color: '#555', fontWeight: 'normal', bgColor: 'transparent', textAlign: 'center', padding: 2, rotation: 0, opacity: 1, flipH: false, zIndex: z++, noStroke: true });
        els.push({ id: uid(), type: 'text', x: colSplit + 6, y: tRowY, w: boxW - 42, h: lineH, text: String(time).toUpperCase(), fontSize: 14, color: '#000000', fontWeight: 'bold', bgColor: 'transparent', textAlign: 'left', padding: 2, rotation: 0, opacity: 1, flipH: false, zIndex: z++, noStroke: true });
      }

      // Reps row
      if (reps) {
        const rRowY = (time ? midY : boxY) + (rowH - lineH) / 2;
        els.push({ id: uid(), type: 'text', x: boxX + 2, y: rRowY, w: 32, h: lineH, text: '\uD83D\uDD01', fontSize: 15, color: '#555', fontWeight: 'normal', bgColor: 'transparent', textAlign: 'center', padding: 2, rotation: 0, opacity: 1, flipH: false, zIndex: z++, noStroke: true });
        els.push({ id: uid(), type: 'text', x: colSplit + 6, y: rRowY, w: boxW - 42, h: lineH, text: String(reps).toUpperCase().replace(/X/g, 'x'), fontSize: 14, color: '#000000', fontWeight: 'bold', bgColor: 'transparent', textAlign: 'left', padding: 2, rotation: 0, opacity: 1, flipH: false, zIndex: z++, noStroke: true });
      }
    }

    // --- Bottom: description centered ---
    if (description) {
      const descStr = String(description).toUpperCase();
      const estLines = Math.max(1, Math.ceil(descStr.length / 50));
      const descH = estLines * (lineH + 2);
      els.push({ id: uid(), type: 'text', x: cW * 0.1, y: cH - 25 - descH, w: cW * 0.8, h: descH, text: descStr, fontSize: 12, color: '#000000', fontWeight: 'bold', bgColor: 'transparent', textAlign: 'center', padding: 2, rotation: 0, opacity: 1, flipH: false, zIndex: z++, noStroke: true });
    }

    setElements(prev => [...prev, ...els]);
  };

  const handleSelect = (id, e) => {
    e.stopPropagation();
    if (selectBoxRef.current) return;
    if (e.ctrlKey || e.metaKey || e.shiftKey) {
      setSelectedIds(prev => prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]);
    } else {
      setSelectedIds([id]);
    }
  };

  const clearSelection = () => { setSelectedIds([]); setEditingTextId(null); };

  const onMouseDownCanvas = (e) => {
    if (e.button !== 0) return;
    const rect = canvasRef.current.getBoundingClientRect();
    const cs = canvasSizeRef.current;
    const sx = cs.w / rect.width;
    const sy = cs.h / rect.height;
    const x = (e.clientX - rect.left) * sx;
    const y = (e.clientY - rect.top) * sy;
    const newBox = { startX: x, startY: y, currentX: x, currentY: y, ctrlKey: e.ctrlKey || e.metaKey, elements: elementsRef.current };
    selectBoxRef.current = newBox;
    setSelectBox(newBox);
  };

  const onMouseUpCanvas = (e) => {
    const sb = selectBoxRef.current;
    if (!sb) return;
    const box = {
      x: Math.min(sb.startX, sb.currentX),
      y: Math.min(sb.startY, sb.currentY),
      w: Math.abs(sb.currentX - sb.startX),
      h: Math.abs(sb.currentY - sb.startY),
    };
    if (box.w > 5 && box.h > 5) {
      const currentElements = sb.elements || elements;
      const intersects = (el) => {
        let ex, ey, ew, eh;
        if (el.type === 'arrow') {
          const b = getArrowBox(el);
          ex = b.x; ey = b.y; ew = b.w; eh = b.h;
        } else {
          const rot = el.rotation || 0;
          if (Math.abs(rot) > 0.5) {
            const cx = el.x + el.w / 2;
            const cy = el.y + el.h / 2;
            const rad = rot * Math.PI / 180;
            const cos = Math.abs(Math.cos(rad));
            const sin = Math.abs(Math.sin(rad));
            ew = el.w * cos + el.h * sin;
            eh = el.w * sin + el.h * cos;
            ex = cx - ew / 2;
            ey = cy - eh / 2;
          } else {
            ex = el.x; ey = el.y; ew = el.w; eh = el.h;
          }
        }
        const margin = 4;
        return !(ex + ew + margin < box.x || ex - margin > box.x + box.w || ey + eh + margin < box.y || ey - margin > box.y + box.h);
      };
      const newSel = currentElements.filter(e => e.type !== 'field' && intersects(e)).map(e => e.id);
      if (sb.ctrlKey) {
        setSelectedIds(prev => [...new Set([...prev, ...newSel])]);
      } else {
        setSelectedIds(newSel);
      }
    } else if (!sb.ctrlKey) {
      setSelectedIds([]); setEditingTextId(null);
      selectBoxRef.current = null;
    }
    setSelectBox(null);
  };

  const onMouseDownEl = (e, el) => {
    if (el.type === 'field') return;
    e.stopPropagation();
    if (editingTextId === el.id) return;
    if (e.button !== 0) return;

    if (e.shiftKey) {
      const rect = canvasRef.current.getBoundingClientRect();
      const cs = canvasSizeRef.current;
      const sx = cs.w / rect.width;
      const sy = cs.h / rect.height;
      const x = (e.clientX - rect.left) * sx;
      const y = (e.clientY - rect.top) * sy;
      const newBox = { startX: x, startY: y, currentX: x, currentY: y, ctrlKey: true };
      selectBoxRef.current = newBox;
      setSelectBox(newBox);
      return;
    }

    const sb = selectBoxRef.current;
    if (sb && (Math.abs(sb.currentX - sb.startX) > 5 || Math.abs(sb.currentY - sb.startY) > 5)) return;
    const rect = canvasRef.current.getBoundingClientRect();
    const cs = canvasSizeRef.current;
    const sx = cs.w / rect.width;
    const sy = cs.h / rect.height;

    if (el.type === 'arrow') {
      const clickX = (e.clientX - rect.left) * sx;
      const clickY = (e.clientY - rect.top) * sy;
      const dStart = Math.hypot(clickX - el.x1, clickY - el.y1);
      const dEnd = Math.hypot(clickX - el.x2, clickY - el.y2);
      if (dStart < 25) {
        if (!selectedIds.includes(el.id)) setSelectedIds(prev => [el.id]);
        const d = { id: el.id, type: 'arrow-start' };
        draggingRef.current = d; setDragging(d);
        return;
      }
      if (dEnd < 25) {
        if (!selectedIds.includes(el.id)) setSelectedIds(prev => [el.id]);
        const d = { id: el.id, type: 'arrow-end' };
        draggingRef.current = d; setDragging(d);
        return;
      }
      const d = { id: el.id, type: 'arrow-move', ox: clickX, oy: clickY, sx: el.x1, sy: el.y1, ex: el.x2, ey: el.y2 };
      draggingRef.current = d; setDragging(d);
      return;
    }

    if (selectedIds.length > 1 && selectedIds.includes(el.id)) {
      const d = { id: el.id, type: 'group-move', ox: (e.clientX - rect.left) * sx, oy: (e.clientY - rect.top) * sy, initial: elements.filter(x => selectedIds.includes(x.id)).map(x => ({ id: x.id, x: x.x, y: x.y, x1: x.x1, y1: x.y1, x2: x.x2, y2: x.y2 })) };
      draggingRef.current = d; setDragging(d);
    } else {
      const d = { id: el.id, type: 'move', ox: (e.clientX - rect.left) * sx - el.x, oy: (e.clientY - rect.top) * sy - el.y };
      draggingRef.current = d; setDragging(d);
    }
  };

  const onMouseDownResize = (e, handle) => {
    e.stopPropagation();
    const el = elements.find(x => x.id === selectedIds[0]);
    if (!el || el.type === 'arrow') return;
    const r = { id: el.id, handle, sx: e.clientX, sy: e.clientY, sw: el.w, sh: el.h, sl: el.x, st: el.y, fontSize: el.fontSize || 0 };
    resizingRef.current = r; setResizing(r);
  };

  const onMouseDownRotate = (e) => {
    e.stopPropagation();
    const el = elements.find(x => x.id === selectedIds[0]);
    if (!el || el.type === 'arrow') return;
    const rect = canvasRef.current.getBoundingClientRect();
    const cs = canvasSizeRef.current;
    const cx = rect.left + (el.x + el.w / 2) * (rect.width / cs.w);
    const cy = rect.top + (el.y + el.h / 2) * (rect.height / cs.h);
    const r = { id: el.id, cx, cy, startAngle: Math.atan2(e.clientY - cy, e.clientX - cx) * 180 / Math.PI, startRot: el.rotation || 0 };
    rotatingRef.current = r; setRotating(r);
  };

  useEffect(() => {
    const onMove = (e) => {
      const sb = selectBoxRef.current;
      if (sb) {
        const rect = canvasRef.current.getBoundingClientRect();
        const cs = canvasSizeRef.current;
        const sx = cs.w / rect.width;
        const sy = cs.h / rect.height;
        const mx = (e.clientX - rect.left) * sx;
        const my = (e.clientY - rect.top) * sy;
        const updated = { ...sb, currentX: mx, currentY: my, elements: elementsRef.current };
        selectBoxRef.current = updated;
        setSelectBox(updated);
      }
      const dg = draggingRef.current;
      if (dg) {
        const rect = canvasRef.current.getBoundingClientRect();
        const cs = canvasSizeRef.current;
        const sx = cs.w / rect.width;
        const sy = cs.h / rect.height;
        const mx = (e.clientX - rect.left) * sx;
        const my = (e.clientY - rect.top) * sy;

        if (dg.type === 'move') {
          setElements(prev => prev.map(el => el.id === dg.id ? { ...el, x: mx - dg.ox, y: my - dg.oy } : el));
        } else if (dg.type === 'group-move') {
          const dx = mx - dg.ox;
          const dy = my - dg.oy;
          setElements(prev => prev.map(el => {
            const ini = dg.initial.find(i => i.id === el.id);
            if (!ini) return el;
            if (el.type === 'arrow') {
              return { ...el, x1: ini.x1 + dx, y1: ini.y1 + dy, x2: ini.x2 + dx, y2: ini.y2 + dy };
            }
            return { ...el, x: ini.x + dx, y: ini.y + dy };
          }));
        } else if (dg.type === 'arrow-start') {
          setElements(prev => prev.map(el => el.id === dg.id ? { ...el, x1: mx, y1: my } : el));
        } else if (dg.type === 'arrow-end') {
          setElements(prev => prev.map(el => el.id === dg.id ? { ...el, x2: mx, y2: my } : el));
        } else if (dg.type === 'arrow-move') {
          const dx = mx - dg.ox;
          const dy = my - dg.oy;
          setElements(prev => prev.map(el => el.id === dg.id ? { ...el, x1: dg.sx + dx, y1: dg.sy + dy, x2: dg.ex + dx, y2: dg.ey + dy } : el));
        }
      }
      const rs = resizingRef.current;
      if (rs) {
        const rect = canvasRef.current.getBoundingClientRect();
        const cs = canvasSizeRef.current;
        const sc = cs.w / rect.width;
        const dx = (e.clientX - rs.sx) * sc;
        const dy = (e.clientY - rs.sy) * sc;
        setElements(prev => prev.map(el => {
          if (el.id !== rs.id) return el;
          let u = {};
          if (el.type === 'number') {
            const deltas = [];
            if (rs.handle.includes('e')) deltas.push(dx);
            if (rs.handle.includes('w')) deltas.push(-dx);
            if (rs.handle.includes('s')) deltas.push(dy);
            if (rs.handle.includes('n')) deltas.push(-dy);
            const delta = deltas.length > 0 ? Math.max(...deltas) : 0;
            const newSize = Math.max(20, rs.sw + delta);
            const ratio = newSize / rs.sw;
            u.w = newSize;
            u.h = newSize;
            u.fontSize = Math.round(rs.fontSize * ratio);
            if (rs.handle.includes('w')) u.x = rs.sl + (rs.sw - newSize);
            if (rs.handle.includes('n')) u.y = rs.st + (rs.sh - newSize);
          } else if (el.type === 'text') {
            if (rs.handle.includes('e')) u.w = Math.max(20, rs.sw + dx);
            if (rs.handle.includes('w')) { u.w = Math.max(20, rs.sw - dx); u.x = rs.sl + (rs.sw - u.w); }
            if (rs.handle.includes('s')) u.h = Math.max(20, rs.sh + dy);
            if (rs.handle.includes('n')) { u.h = Math.max(20, rs.sh - dy); u.y = rs.st + (rs.sh - u.h); }
          } else {
            if (rs.handle.includes('e')) u.w = Math.max(20, rs.sw + dx);
            if (rs.handle.includes('w')) { u.w = Math.max(20, rs.sw - dx); u.x = rs.sl + (rs.sw - u.w); }
            if (rs.handle.includes('s')) u.h = Math.max(20, rs.sh + dy);
            if (rs.handle.includes('n')) { u.h = Math.max(20, rs.sh - dy); u.y = rs.st + (rs.sh - u.h); }
          }
          return { ...el, ...u };
        }));
      }
      const rt = rotatingRef.current;
      if (rt) {
        const angle = Math.atan2(e.clientY - rt.cy, e.clientX - rt.cx) * 180 / Math.PI;
        setElements(prev => prev.map(el => el.id === rt.id ? { ...el, rotation: rt.startRot + (angle - rt.startAngle) } : el));
      }
    };
    const onUp = () => {
      const sb = selectBoxRef.current;
      if (sb) {
        const box = {
          x: Math.min(sb.startX, sb.currentX),
          y: Math.min(sb.startY, sb.currentY),
          w: Math.abs(sb.currentX - sb.startX),
          h: Math.abs(sb.currentY - sb.startY),
        };
        if (box.w > 5 && box.h > 5) {
          const currentElements = sb.elements || elementsRef.current;
          const intersects = (el) => {
            let ex, ey, ew, eh;
            if (el.type === 'arrow') {
              const b = getArrowBox(el);
              ex = b.x; ey = b.y; ew = b.w; eh = b.h;
            } else {
              const rot = el.rotation || 0;
              if (Math.abs(rot) > 0.5) {
                const cx = el.x + el.w / 2;
                const cy = el.y + el.h / 2;
                const rad = rot * Math.PI / 180;
                const cos = Math.abs(Math.cos(rad));
                const sin = Math.abs(Math.sin(rad));
                ew = el.w * cos + el.h * sin;
                eh = el.w * sin + el.h * cos;
                ex = cx - ew / 2;
                ey = cy - eh / 2;
              } else {
                ex = el.x; ey = el.y; ew = el.w; eh = el.h;
              }
            }
            const margin = 4;
            return !(ex + ew + margin < box.x || ex - margin > box.x + box.w || ey + eh + margin < box.y || ey - margin > box.y + box.h);
          };
          const newSel = currentElements.filter(e => e.type !== 'field' && intersects(e)).map(e => e.id);
          if (sb.ctrlKey) {
            setSelectedIds(prev => [...new Set([...prev, ...newSel])]);
          } else {
            setSelectedIds(newSel);
          }
        } else if (!sb.ctrlKey) {
          setSelectedIds([]); setEditingTextId(null);
        }
        selectBoxRef.current = null;
        setSelectBox(null);
      }
      const wasInteracting = draggingRef.current || resizingRef.current || rotatingRef.current;
      draggingRef.current = null; setDragging(null);
      resizingRef.current = null; setResizing(null);
      rotatingRef.current = null; setRotating(null);
      if (wasInteracting) pushHistoryRef.current?.();
    };
    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
    return () => { window.removeEventListener('mousemove', onMove); window.removeEventListener('mouseup', onUp); };
  }, []);

  const updateSelected = (updates) => {
    if (!draggingRef.current && !resizingRef.current && !rotatingRef.current) pushHistory();
    setElements(prev => prev.map(el => selectedIds.includes(el.id) ? { ...el, ...updates } : el));
  };

  const deleteSelected = () => {
    pushHistory();
    setElements(prev => prev.filter(el => !selectedIds.includes(el.id)));
    setSelectedIds([]);
  };

  const clearOverlays = () => {
    pushHistory();
    setElements(prev => prev.filter(el => el.type === 'field'));
    setSelectedIds([]);
  };

  const bringForward = () => {
    const mx = Math.max(...elements.map(e => e.zIndex), 0);
    updateSelected({ zIndex: mx + 1 });
  };

  const sendBackward = () => {
    const mn = Math.min(...elements.map(e => e.zIndex), 0);
    updateSelected({ zIndex: mn - 1 });
  };

  const alignHorizontal = () => {
    if (selectedIds.length < 2) return;
    const sel = elements.filter(e => selectedIds.includes(e.id));
    const avgY = sel.reduce((sum, e) => sum + (e.type === 'arrow' ? (e.y1 + e.y2) / 2 : e.y + e.h / 2), 0) / sel.length;
    setElements(prev => prev.map(el => {
      if (!selectedIds.includes(el.id)) return el;
      if (el.type === 'arrow') {
        const midY = (el.y1 + el.y2) / 2;
        const dy = avgY - midY;
        return { ...el, y1: el.y1 + dy, y2: el.y2 + dy };
      }
      return { ...el, y: avgY - el.h / 2 };
    }));
  };

  const alignVertical = () => {
    if (selectedIds.length < 2) return;
    const sel = elements.filter(e => selectedIds.includes(e.id));
    const avgX = sel.reduce((sum, e) => sum + (e.type === 'arrow' ? (e.x1 + e.x2) / 2 : e.x + e.w / 2), 0) / sel.length;
    setElements(prev => prev.map(el => {
      if (!selectedIds.includes(el.id)) return el;
      if (el.type === 'arrow') {
        const midX = (el.x1 + el.x2) / 2;
        const dx = avgX - midX;
        return { ...el, x1: el.x1 + dx, x2: el.x2 + dx };
      }
      return { ...el, x: avgX - el.w / 2 };
    }));
  };

  const distributeHorizontal = () => {
    if (selectedIds.length < 3) return;
    const sel = elements.filter(e => selectedIds.includes(e.id));
    const sorted = [...sel].sort((a, b) => {
      const ax = a.type === 'arrow' ? (a.x1 + a.x2) / 2 : a.x;
      const bx = b.type === 'arrow' ? (b.x1 + b.x2) / 2 : b.x;
      return ax - bx;
    });
    const first = sorted[0], last = sorted[sorted.length - 1];
    const left = first.type === 'arrow' ? (first.x1 + first.x2) / 2 : first.x;
    const right = last.type === 'arrow' ? (last.x1 + last.x2) / 2 : last.x;
    const totalSpace = right - left;
    const gap = totalSpace / (sorted.length - 1);
    setElements(prev => prev.map(el => {
      if (!selectedIds.includes(el.id)) return el;
      const idx = sorted.indexOf(el);
      if (idx <= 0 || idx >= sorted.length - 1) return el;
      const targetX = left + gap * idx;
      if (el.type === 'arrow') {
        const midX = (el.x1 + el.x2) / 2;
        const dx = targetX - midX;
        return { ...el, x1: el.x1 + dx, x2: el.x2 + dx };
      }
      return { ...el, x: targetX };
    }));
  };

  const distributeVertical = () => {
    if (selectedIds.length < 3) return;
    const sel = elements.filter(e => selectedIds.includes(e.id));
    const sorted = [...sel].sort((a, b) => {
      const ay = a.type === 'arrow' ? (a.y1 + a.y2) / 2 : a.y;
      const by = b.type === 'arrow' ? (b.y1 + b.y2) / 2 : b.y;
      return ay - by;
    });
    const first = sorted[0], last = sorted[sorted.length - 1];
    const top = first.type === 'arrow' ? (first.y1 + first.y2) / 2 : first.y;
    const bottom = last.type === 'arrow' ? (last.y1 + last.y2) / 2 : last.y;
    const totalSpace = bottom - top;
    const gap = totalSpace / (sorted.length - 1);
    setElements(prev => prev.map(el => {
      if (!selectedIds.includes(el.id)) return el;
      const idx = sorted.indexOf(el);
      if (idx <= 0 || idx >= sorted.length - 1) return el;
      const targetY = top + gap * idx;
      if (el.type === 'arrow') {
        const midY = (el.y1 + el.y2) / 2;
        const dy = targetY - midY;
        return { ...el, y1: el.y1 + dy, y2: el.y2 + dy };
      }
      return { ...el, y: targetY };
    }));
  };

  const selectedEls = elements.filter(e => selectedIds.includes(e.id));
  const primarySelected = selectedEls[0];

  const duplicateSelected = () => {
    if (!primarySelected) return;
    pushHistory();
    const id = uid();
    let duplicated;
    if (primarySelected.type === 'arrow') {
      duplicated = { ...primarySelected, id, x1: primarySelected.x1 + 20, y1: primarySelected.y1 + 20, x2: primarySelected.x2 + 20, y2: primarySelected.y2 + 20 };
    } else if (primarySelected.type === 'number') {
      duplicated = { ...primarySelected, id, x: primarySelected.x + 20, y: primarySelected.y + 20, number: (primarySelected.number || 1) + 1 };
    } else {
      duplicated = { ...primarySelected, id, x: primarySelected.x + 20, y: primarySelected.y + 20 };
    }
    setElements(prev => [...prev, duplicated]);
    setSelectedIds([id]);
  };

  const copySelected = () => {
    if (!primarySelected) return;
    const { ...rest } = primarySelected;
    setClipboard({ ...rest });
    setPasteCount(0);
  };

  const pasteClipboard = () => {
    if (!clipboard) return;
    const id = uid();
    const offset = (pasteCount + 1) * 20;
    setPasteCount(prev => prev + 1);
    let pasted;
    if (clipboard.type === 'arrow') {
      pasted = { ...clipboard, id, x1: clipboard.x1 + offset, y1: clipboard.y1 + offset, x2: clipboard.x2 + offset, y2: clipboard.y2 + offset };
    } else {
      pasted = { ...clipboard, id, x: clipboard.x + offset, y: clipboard.y + offset };
    }
    setElements(prev => [...prev, pasted]);
    setSelectedIds([id]);
  };

  useEffect(() => {
    const onKey = (e) => {
      const tag = e.target?.tagName;
      if (editingTextId || tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return;
      if ((e.ctrlKey || e.metaKey) && e.key === 'c') {
        e.preventDefault();
        copySelected();
      }
      if ((e.ctrlKey || e.metaKey) && e.key === 'v') {
        e.preventDefault();
        pasteClipboard();
      }
      if (e.key === 'Delete' || e.key === 'Backspace') {
        if (selectedIds.length > 0) {
          e.preventDefault();
          deleteSelected();
        }
      }
      if (e.key === 'Escape') {
        setSelectedIds([]);
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [primarySelected, clipboard, editingTextId, selectedIds, pasteCount]);

  const capture = async () => {
    try {
      setSelectedIds([]);
      setEditingTextId(null);
      setSelectBox(null);
      document.activeElement?.blur();

      await new Promise(resolve => {
        requestAnimationFrame(() => setTimeout(resolve, 80));
      });

      const el = canvasRef.current;
      if (!el) return;

      const styleTag = document.createElement('style');
      styleTag.id = 'capture-override';
      styleTag.textContent = `
        * { box-shadow: none !important; outline: none !important; }
        *:not(.preserve-border) { border: none !important; }
        img { background: transparent !important; padding: 0 !important; margin: 0 !important; }
        .ring-2, .ring-gk-accent { box-shadow: none !important; outline: none !important; }
      `;
      el.appendChild(styleTag);

      await new Promise(resolve => setTimeout(resolve, 50));

      const domtoimage = await import('dom-to-image-more');
      const dataUrl = await domtoimage.toPng(el, {
        quality: 1,
        scale: 3,
        bgcolor: '#ffffff',
        width: canvasSizeRef.current.w,
        height: canvasSizeRef.current.h,
        style: { transform: 'none', transformOrigin: 'top left' },
      });

      styleTag.remove();

      const res = await fetch(dataUrl);
      const blob = await res.blob();
      if (blob) { onSave(blob, elementsRef.current); }
      else { alert('Error: no se pudo generar la imagen'); }
    } catch (err) {
      console.error('Capture error:', err);
      alert('Error al capturar la imagen: ' + err.message);
    }
  };

  const LARGE_OBJECT_CATEGORIES = new Set(['muñecos', 'picas', 'porterías', 'varios']);

  const addImageWithSize = (type, src, maxDim = 20) => {
    const img = new Image();
    img.onload = () => {
      let nw, nh;
      if (img.naturalWidth > img.naturalHeight) {
        nw = maxDim;
        nh = Math.round(maxDim * img.naturalHeight / img.naturalWidth);
      } else {
        nh = maxDim;
        nw = Math.round(maxDim * img.naturalWidth / img.naturalHeight);
      }
      addElement(type, { src, w: nw, h: nh, defaultDim: maxDim });
    };
    img.onerror = () => addElement(type, { src });
    img.src = src;
  };

  const handleUpload = (e) => {
    const file = e.target.files[0]; if (!file) return;
    const url = URL.createObjectURL(file);
    addImageWithSize('image', url);
  };

  const handleAddObjectFromFile = (e) => {
    const file = e.target.files[0]; if (!file) return;
    const url = URL.createObjectURL(file);
    addImageWithSize('image', url);
    setShowAddObjectModal(false);
  };

  const handleAddObjectFromUrl = () => {
    if (!objectUrl.trim()) return;
    addImageWithSize('image', objectUrl.trim());
    setShowAddObjectModal(false);
    setObjectUrl('');
  };

  const handlePasteImage = async () => {
    try {
      const clipboardItems = await navigator.clipboard.read();
      for (const item of clipboardItems) {
        for (const type of item.types) {
          if (type.startsWith('image/')) {
            const blob = await item.getType(type);
            const url = URL.createObjectURL(blob);
            addImageWithSize('image', url);
            setShowAddObjectModal(false);
            return;
          }
        }
      }
      alert('No se encontró ninguna imagen en el portapapeles');
    } catch (err) {
      console.error('Paste error:', err);
      alert('No se pudo acceder al portapapeles. Asegúrate de dar permisos al navegador.');
    }
  };

  const handleAddText = () => {
    if (!textInputValue.trim()) return;
    addElement('text', { text: textInputValue.trim() });
    setShowTextInputModal(false);
    setTextInputValue('');
  };

  const saveShapePreset = () => {
    if (!primarySelected || !['rect', 'circle', 'triangle', 'arrow'].includes(primarySelected.type)) return;
    const shapeType = primarySelected.type;
    const name = presetName.trim() || `Preset ${shapePresets[shapeType].length + 1}`;
    let preset;
    if (shapeType === 'arrow') {
      preset = {
        id: uid(),
        name,
        stroke: primarySelected.stroke,
        strokeWidth: primarySelected.strokeWidth,
        strokeStyle: primarySelected.strokeStyle,
        headStyle: primarySelected.headStyle,
        doubleHead: primarySelected.doubleHead,
        headSize: primarySelected.headSize,
      };
    } else {
      preset = {
        id: uid(),
        name,
        stroke: primarySelected.stroke,
        strokeWidth: primarySelected.strokeWidth,
        strokeStyle: primarySelected.strokeStyle,
        fill: primarySelected.fill,
        fillType: primarySelected.fillType,
        fillOpacity: primarySelected.fillOpacity,
      };
    }
    const updated = { ...shapePresets, [shapeType]: [...shapePresets[shapeType], preset] };
    setShapePresets(updated);
    setSetting('drawingPresets', updated);
    setShowPresetName(false);
    setPresetName('');
  };

  const loadShapePreset = (preset) => {
    if (!primarySelected || !['rect', 'circle', 'triangle', 'arrow'].includes(primarySelected.type)) return;
    if (primarySelected.type === 'arrow') {
      updateSelected({
        stroke: preset.stroke,
        strokeWidth: preset.strokeWidth,
        strokeStyle: preset.strokeStyle,
        headStyle: preset.headStyle,
        doubleHead: preset.doubleHead,
        headSize: preset.headSize,
      });
    } else {
      updateSelected({
        stroke: preset.stroke,
        strokeWidth: preset.strokeWidth,
        strokeStyle: preset.strokeStyle,
        fill: preset.fill,
        fillType: preset.fillType,
        fillOpacity: preset.fillOpacity,
      });
    }
  };

  const deleteShapePreset = (id) => {
    if (!primarySelected || !['rect', 'circle', 'triangle', 'arrow'].includes(primarySelected.type)) return;
    const shapeType = primarySelected.type;
    const updated = { ...shapePresets, [shapeType]: shapePresets[shapeType].filter(p => p.id !== id) };
    setShapePresets(updated);
    setSetting('drawingPresets', updated);
  };

  const stripedStyle = (color, opacity = 0.15) => {
    const hexOpacity = Math.round(opacity * 255).toString(16).padStart(2, '0');
    const lightOpacity = Math.round(opacity * 0.3 * 255).toString(16).padStart(2, '0');
    return {
      background: `repeating-linear-gradient(-45deg, ${color}${hexOpacity}, ${color}${hexOpacity} 6px, ${color}${lightOpacity} 6px, ${color}${lightOpacity} 12px)`,
    };
  };

  return (
    <div className="flex flex-col h-full">
      <div className="sticky top-0 z-10 pb-4 pt-4 px-5 shrink-0" style={{background: 'rgba(12,11,9,0.95)', backdropFilter: 'blur(12px)', borderBottom: '1px solid rgba(185,165,135,0.08)'}}>
        <div className="flex items-center justify-between flex-wrap gap-3">
          <h2 className="text-lg font-bold" style={{color: '#f1ede7'}}>Editor de imagen</h2>
          <div className="flex gap-2 flex-wrap items-center">
            <button onClick={() => fileInputRef.current?.click()} className="v2-btn-ghost">
              <LayoutTemplate size={14} /> Subir imagen
            </button>

            <button onClick={clearOverlays} className="px-3 py-1.5 rounded-lg text-sm font-medium flex items-center gap-2 transition-all" style={{background: 'rgba(220,38,38,0.10)', color: '#fca5a5', border: '1px solid rgba(220,38,38,0.12)'}}>
              <RotateCcw size={14} /> Limpiar
            </button>
            <button onClick={onCancel} className="v2-btn-ghost">
              Cancelar
            </button>
          </div>
        </div>
        <input ref={fileInputRef} type="file" accept="image/*" className="hidden" onChange={handleUpload} />
        <input ref={objectFileInputRef} type="file" accept="image/*" className="hidden" onChange={handleAddObjectFromFile} />
      </div>

      {showAddObjectModal && (
        <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4">
          <div className="bg-gk-card rounded-xl border border-gk-border p-6 w-full max-w-md space-y-4">
            <h3 className="text-lg font-bold text-gk-text-primary">Añadir objeto</h3>

            <div>
              <label className="block text-sm font-medium text-gk-text-tertiary mb-2">Desde archivo</label>
              <button onClick={() => objectFileInputRef?.current?.click()} className="w-full px-4 py-2 bg-gk-elevated hover:bg-gk-elevated rounded-lg text-gk-text-primary flex items-center justify-center gap-2 transition-colors">
                <LayoutTemplate size={16} /> Seleccionar imagen
              </button>
            </div>

            <div>
              <label className="block text-sm font-medium text-gk-text-tertiary mb-2">Desde enlace web</label>
              <div className="flex gap-2">
                <input type="text" value={objectUrl} onChange={e => setObjectUrl(e.target.value)} placeholder="https://ejemplo.com/imagen.png" className="flex-1 px-3 py-2 bg-gk-page border border-gk-border rounded-lg text-sm text-gk-text-primary focus:outline-none focus:border-gk-accent" />
                <button onClick={handleAddObjectFromUrl} className="px-4 py-2 bg-gk-accent hover:bg-gk-accent rounded-lg text-white flex items-center gap-1 transition-colors">
                  <Link size={14} /> Añadir
                </button>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gk-text-tertiary mb-2">Desde portapapeles</label>
              <button onClick={handlePasteImage} className="w-full px-4 py-2 bg-gk-elevated hover:bg-gk-elevated rounded-lg text-gk-text-primary flex items-center justify-center gap-2 transition-colors">
                <Clipboard size={16} /> Pegar imagen
              </button>
            </div>

            <div className="flex justify-end pt-2">
              <button onClick={() => { setShowAddObjectModal(false); setObjectUrl(''); }} className="px-4 py-2 bg-gk-elevated hover:bg-gk-elevated rounded-lg text-gk-text-primary transition-colors">
                Cancelar
              </button>
            </div>
          </div>
        </div>
      )}

      {showTextInputModal && (
        <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4">
          <div className="bg-gk-card rounded-xl border border-gk-border p-6 w-full max-w-md space-y-4">
            <h3 className="text-lg font-bold text-gk-text-primary">Añadir texto</h3>
            <textarea
              value={textInputValue}
              onChange={e => setTextInputValue(e.target.value)}
              placeholder="Escribe el texto..."
              rows={4}
              autoFocus
              className="w-full px-3 py-2 bg-gk-page border border-gk-border rounded-lg text-sm text-gk-text-primary focus:outline-none focus:border-gk-accent resize-none"
              onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleAddText(); } }}
            />
            <div className="flex gap-2 justify-end">
              <button onClick={() => setShowTextInputModal(false)} className="px-4 py-2 bg-gk-elevated hover:bg-gk-elevated rounded-lg text-gk-text-primary transition-colors">
                Cancelar
              </button>
              <button onClick={handleAddText} disabled={!textInputValue.trim()} className="px-4 py-2 bg-gk-accent hover:bg-gk-accent disabled:opacity-50 rounded-lg text-white transition-colors">
                Añadir
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="flex flex-1 gap-3 min-h-0">
        <div className="w-56 bg-gk-card rounded-xl border border-gk-border flex flex-col overflow-hidden shrink-0">
          <div className="flex border-b border-gk-border">
            {[
              { key: 'fields', icon: LayoutTemplate, label: 'Campos' },
              { key: 'objects', icon: Paintbrush, label: 'Objetos' },
              { key: 'shapes', icon: Square, label: 'Formas' },
              { key: 'text', icon: Type, label: 'Texto' },
            ].map(t => (
              <button key={t.key} onClick={() => setToolTab(t.key)} className={`flex-1 py-2 text-xs font-medium transition-colors ${toolTab === t.key ? 'bg-gk-elevated text-gk-accent' : 'text-gk-text-tertiary hover:bg-gk-elevated/50'}`}>
                <t.icon size={14} className="mx-auto mb-0.5" /> {t.label}
              </button>
            ))}
          </div>
          <div className="flex-1 overflow-y-auto p-2 space-y-2">
            {toolTab === 'fields' && FIELDS.map(f => (
              <button key={f.id} onClick={() => addElement('field', { src: f.src })} className="w-full text-left p-2 rounded hover:bg-gk-elevated transition-colors">
                <img src={f.src} alt={f.name} className="w-full h-20 object-contain bg-gk-page rounded mb-1" />
                <div className="text-xs text-gk-text-secondary">{f.name}</div>
              </button>
            ))}
            {toolTab === 'objects' && (
              <>
                <div className="p-2">
                  <button onClick={() => setShowAddObjectModal(true)} className="w-full p-2 bg-indigo-600 hover:bg-indigo-500 rounded text-sm text-white font-medium flex items-center justify-center gap-2"><Plus size={16} /> Añadir objeto</button>
                  <input
                    type="text"
                    value={objectSearch}
                    onChange={e => setObjectSearch(e.target.value)}
                    placeholder="Buscar objeto..."
                    className="w-full mt-2 px-2 py-1.5 bg-gk-page border border-gk-border-hover rounded text-xs text-gk-text-primary placeholder-gk-text-tertiary focus:outline-none focus:border-gk-accent"
                  />
                </div>
                {OBJECTS_BY_CATEGORY
                  .filter(cat => {
                    if (!objectSearch.trim()) return true;
                    const q = normalize(objectSearch);
                    return normalize(cat.label).includes(q) || cat.items.some(o => normalize(o.name).includes(q));
                  })
                  .map(cat => {
                  const isExpanded = expandedCategories.has(cat.key) || (objectSearch.trim() && cat.items.some(o => normalize(o.name).includes(normalize(objectSearch))));
                  const catMaxDim = LARGE_OBJECT_CATEGORIES.has(cat.key) ? 120 : 20;
                  const filteredItems = objectSearch.trim()
                    ? cat.items.filter(o => normalize(o.name).includes(normalize(objectSearch)))
                    : cat.items;
                  return (
                    <div key={cat.key} className="mb-1">
                      <button
                        onClick={() => {
                          setExpandedCategories(prev => {
                            const next = new Set(prev);
                            if (next.has(cat.key)) next.delete(cat.key);
                            else next.add(cat.key);
                            return next;
                          });
                        }}
                        className="w-full flex items-center justify-between px-2 py-1.5 rounded hover:bg-gk-elevated/60 transition-colors text-xs font-semibold text-gk-text-primary uppercase tracking-wide"
                      >
                        <span>{cat.label}</span>
                        {isExpanded ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                      </button>
                      {isExpanded && (
                        <div className="space-y-1 px-1 pt-1">
                          {filteredItems.map(o => (
                            <button key={o.id} onClick={() => addImageWithSize('object', o.src, catMaxDim)} className="w-full text-left p-2 rounded hover:bg-gk-elevated transition-colors">
                              <img src={o.src} alt={o.name} className={`w-full ${catMaxDim > 20 ? 'h-16' : 'h-8'} object-contain bg-transparent rounded mb-1`} style={{ border: 'none', background: 'transparent' }} />
                              <div className="text-xs text-gk-text-secondary capitalize">{o.name}</div>
                            </button>
                          ))}
                        </div>
                      )}
                    </div>
                  );
                })}
              </>
            )}
            {toolTab === 'shapes' && (
              <div className="space-y-2 p-2">
                <button onClick={() => addElement('rect')} className="w-full p-2 bg-gk-elevated hover:bg-gk-elevated rounded flex items-center gap-2 text-sm text-gk-text-primary"><Square size={16} /> Rectángulo</button>
                <button onClick={() => addElement('circle')} className="w-full p-2 bg-gk-elevated hover:bg-gk-elevated rounded flex items-center gap-2 text-sm text-gk-text-primary"><Circle size={16} /> Círculo</button>
                <button onClick={() => addElement('triangle')} className="w-full p-2 bg-gk-elevated hover:bg-gk-elevated rounded flex items-center gap-2 text-sm text-gk-text-primary"><Triangle size={16} /> Triángulo</button>
                <button onClick={() => addElement('arrow')} className="w-full p-2 bg-gk-elevated hover:bg-gk-elevated rounded flex items-center gap-2 text-sm text-gk-text-primary"><ArrowRight size={16} /> Flecha</button>
              </div>
            )}
            {toolTab === 'text' && (
              <div className="p-2 space-y-2">
                <button onClick={() => { setTextInputValue(''); setShowTextInputModal(true); }} className="w-full p-2 bg-gk-accent hover:bg-gk-accent rounded text-sm text-white font-medium">+ Añadir texto</button>
                <button onClick={() => addElement('number')} className="w-full p-2 bg-indigo-600 hover:bg-indigo-500 rounded text-sm text-white font-medium flex items-center justify-center gap-2"><Hash size={16} /> Añadir número</button>
              </div>
            )}
          </div>
        </div>

        <div className="flex-1 rounded-xl overflow-auto flex flex-col items-center justify-center gap-4 p-4" style={{background: 'rgba(22,20,16,0.4)', border: '1px solid rgba(185,165,135,0.08)'}} onMouseUp={onMouseUpCanvas}>
          <div
            ref={canvasRef}
            className="relative bg-white select-none shrink-0"
            style={{ width: canvasSize.w, height: canvasSize.h }}
            onMouseDown={onMouseDownCanvas}
          >
            {elements.sort((a,b) => a.zIndex - b.zIndex).map(el => {
              const isSelected = selectedIds.includes(el.id);
              if (el.type === 'arrow') {
                const box = getArrowBox(el);
                const headSizeVal = el.headSize || 4;
                const padding = headSizeVal * 3;
                return (
                  <div key={el.id} className="absolute" style={{ left: box.x - padding, top: box.y - padding, width: box.w + padding * 2, height: box.h + padding * 2, zIndex: el.zIndex, transform: `scaleX(${el.flipH ? -1 : 1})` }}>
                    <svg width="100%" height="100%" viewBox={`${-padding} ${-padding} ${box.w + padding * 2} ${box.h + padding * 2}`} className="pointer-events-none overflow-visible">
                      <defs>
                        <marker id={`aend-${el.id}`} markerWidth={headSizeVal} markerHeight={headSizeVal} refX={headSizeVal * 0.8} refY={headSizeVal / 2} orient="auto">
                          {el.headStyle === 'round' ? (
                            <circle cx={headSizeVal / 2} cy={headSizeVal / 2} r={headSizeVal * 0.4} fill={el.stroke} />
                          ) : (
                            <polygon points={`0 0, ${headSizeVal} ${headSizeVal / 2}, 0 ${headSizeVal}`} fill={el.stroke} />
                          )}
                        </marker>
                        {el.doubleHead && (
                          <marker id={`astart-${el.id}`} markerWidth={headSizeVal} markerHeight={headSizeVal} refX={headSizeVal * 0.2} refY={headSizeVal / 2} orient="auto">
                            {el.headStyle === 'round' ? (
                              <circle cx={headSizeVal / 2} cy={headSizeVal / 2} r={headSizeVal * 0.4} fill={el.stroke} />
                            ) : (
                              <polygon points={`${headSizeVal} 0, 0 ${headSizeVal / 2}, ${headSizeVal} ${headSizeVal}`} fill={el.stroke} />
                            )}
                          </marker>
                        )}
                      </defs>
                      <line x1={el.x1 - box.x} y1={el.y1 - box.y} x2={el.x2 - box.x} y2={el.y2 - box.y} stroke={el.stroke} strokeWidth={el.strokeWidth} strokeDasharray={el.strokeStyle === 'dashed' ? '8 6' : undefined} markerEnd={`url(#aend-${el.id})`} markerStart={el.doubleHead ? `url(#astart-${el.id})` : undefined} />
                    </svg>
                    <div className="absolute inset-0" style={{ cursor: 'move' }} onMouseDown={(e) => onMouseDownEl(e, el)} onClick={(e) => handleSelect(el.id, e)} />
                    {isSelected && (
                      <>
                        <div className="absolute w-3 h-3 bg-blue-500 border-2 border-white rounded-full -translate-x-1/2 -translate-y-1/2 cursor-grab z-20" style={{ left: el.x1 - box.x + padding, top: el.y1 - box.y + padding }} onMouseDown={(e) => { e.stopPropagation(); handleSelect(el.id, e); const d = { id: el.id, type: 'arrow-start' }; draggingRef.current = d; setDragging(d); }} />
                        <div className="absolute w-3 h-3 bg-blue-500 border-2 border-white rounded-full -translate-x-1/2 -translate-y-1/2 cursor-grab z-20" style={{ left: el.x2 - box.x + padding, top: el.y2 - box.y + padding }} onMouseDown={(e) => { e.stopPropagation(); handleSelect(el.id, e); const d = { id: el.id, type: 'arrow-end' }; draggingRef.current = d; setDragging(d); }} />
                      </>
                    )}
                  </div>
                );
              }

              return (
                <div
                  key={el.id}
                  className={`absolute ${isSelected && el.type !== 'field' ? 'ring-2 ring-gk-accent' : ''}`}
                  style={{ left: el.x, top: el.y, width: el.w, height: el.h, transform: el.type !== 'field' ? `rotate(${el.rotation || 0}deg) scaleX(${el.flipH ? -1 : 1})` : undefined, opacity: el.opacity, zIndex: el.zIndex, cursor: el.type === 'field' ? 'default' : 'move' }}
                  onMouseDown={(e) => onMouseDownEl(e, el)}
                  onClick={(e) => { if (el.type === 'field') return; handleSelect(el.id, e); }}
                  onDoubleClick={(e) => { if (el.type === 'text') { e.stopPropagation(); setEditingTextId(el.id); } }}
                >
                  {el.type === 'field' && <img src={el.src} alt="" className="w-full h-full object-cover pointer-events-none" draggable={false} />}
                  {el.type === 'object' && <img src={el.src} alt="" className="w-full h-full object-contain pointer-events-none" draggable={false} style={{ border: 'none', background: 'transparent' }} />}
                  {el.type === 'image' && <img src={el.src} alt="" className="w-full h-full object-contain pointer-events-none" draggable={false} style={{ border: 'none', background: 'transparent' }} />}
                  {el.type === 'rect' && (
                    <div className="w-full h-full preserve-border" style={{
                      ...(el.fillType === 'striped' ? stripedStyle(el.fill !== 'transparent' ? el.fill : el.stroke, el.fillOpacity) :
                        el.fillType === 'solid' ? { backgroundColor: el.fill } : { backgroundColor: 'transparent' }),
                      border: `${el.strokeWidth}px ${el.strokeStyle === 'dashed' ? 'dashed' : 'solid'} ${el.stroke}`,
                    }} />
                  )}
                  {el.type === 'circle' && (
                    <div className="w-full h-full rounded-full preserve-border" style={{
                      ...(el.fillType === 'striped' ? stripedStyle(el.fill !== 'transparent' ? el.fill : el.stroke, el.fillOpacity) :
                        el.fillType === 'solid' ? { backgroundColor: el.fill } : { backgroundColor: 'transparent' }),
                      border: `${el.strokeWidth}px ${el.strokeStyle === 'dashed' ? 'dashed' : 'solid'} ${el.stroke}`,
                    }} />
                  )}
                  {el.type === 'triangle' && (
                    <div className="w-full h-full" style={{ position: 'relative' }}>
                      <svg className="absolute inset-0 w-full h-full" viewBox="0 0 100 100" preserveAspectRatio="none">
                        <polygon points="50,5 95,95 5,95" fill={el.fillType === 'solid' ? el.fill : el.fillType === 'striped' ? (el.fill !== 'transparent' ? el.fill : el.stroke) : 'none'} fillOpacity={el.fillType === 'striped' ? (el.fillOpacity ?? 0.2) : el.fillType === 'solid' ? 1 : 0} stroke={el.stroke} strokeWidth={Math.max(1, el.strokeWidth / Math.max(el.w, el.h) * 100)} strokeDasharray={el.strokeStyle === 'dashed' ? '8 6' : undefined} />
                      </svg>
                      {el.fillType === 'striped' && (
                        <svg className="absolute inset-0 w-full h-full" viewBox="0 0 100 100" preserveAspectRatio="none">
                          <defs>
                            <clipPath id={'tri-clip-' + el.id}>
                              <polygon points="50,5 95,95 5,95" />
                            </clipPath>
                          </defs>
                          <rect x="0" y="0" width="100" height="100" clipPath={'url(#tri-clip-' + el.id + ')'} fill={'url(#stripe-' + el.id + ')'} />
                          <pattern id={'stripe-' + el.id} patternUnits="userSpaceOnUse" width="28.28" height="28.28" patternTransform="rotate(45)">
                            <rect width="28.28" height="28.28" fill="transparent" />
                            <line x1="0" y1="0" x2="0" y2="28.28" stroke={el.fill !== 'transparent' ? el.fill : el.stroke} strokeWidth="10" opacity={el.fillOpacity ?? 0.2} />
                            <line x1="14.14" y1="0" x2="14.14" y2="28.28" stroke={el.fill !== 'transparent' ? el.fill : el.stroke} strokeWidth="10" opacity={(el.fillOpacity ?? 0.2) * 0.5} />
                          </pattern>
                        </svg>
                      )}
                    </div>
                  )}
                  {el.type === 'text' && (
                    editingTextId === el.id ? (
                      <textarea autoFocus className="w-full h-full outline-none resize-none bg-transparent border-0" style={{ fontSize: el.fontSize, color: el.color, fontWeight: el.fontWeight, lineHeight: 1.2, padding: el.padding || 4, textAlign: el.textAlign || 'left' }} value={el.text} onChange={(e) => updateSelected({ text: e.target.value })} onBlur={() => setEditingTextId(null)} onMouseDown={(e) => e.stopPropagation()} />
                    ) : (
                      <div className="w-full h-full flex items-center pointer-events-none" style={{
                        fontSize: el.fontSize, color: el.color, fontWeight: el.fontWeight, lineHeight: 1.2,
                        backgroundColor: el.bgColor || 'transparent', padding: el.padding || 4,
                        whiteSpace: 'pre-wrap', wordBreak: 'break-word', textAlign: el.textAlign || 'left',
                        justifyContent: el.textAlign === 'center' ? 'center' : el.textAlign === 'right' ? 'flex-end' : 'flex-start',
                        ...(el.noStroke ? {} : { border: `${el.strokeWidth}px solid ${el.stroke}`, borderRadius: 4 }),
                      }}>
                        {el.text}
                      </div>
                    )
                  )}
                  {el.type === 'number' && (
                    <div className="w-full h-full rounded-full flex items-center justify-center pointer-events-none preserve-border" style={{
                      ...(el.bgColor !== 'transparent' ? { backgroundColor: el.bgColor } : {}),
                      ...(el.noStroke ? {} : { border: `${el.strokeWidth}px solid ${el.stroke}` }),
                    }}>
                      <span style={{ fontSize: el.fontSize, color: el.numberColor, fontWeight: el.fontWeight, lineHeight: 1 }}>
                        {el.number}
                      </span>
                    </div>
                  )}

                  {isSelected && el.type !== 'field' && el.type !== 'arrow' && (
                    <>
                      <div className="absolute inset-0" style={{ transform: `rotate(${-(el.rotation || 0)}deg)`, transformOrigin: 'center center' }}>
                        {['nw','ne','sw','se'].map(h => (
                          <div key={h} className="absolute w-3 h-3 bg-gk-accent border border-white rounded-full z-20" style={{ top: h.includes('n') ? -6 : 'auto', bottom: h.includes('s') ? -6 : 'auto', left: h.includes('w') ? -6 : 'auto', right: h.includes('e') ? -6 : 'auto', cursor: h === 'nw' || h === 'se' ? 'nwse-resize' : 'nesw-resize' }} onMouseDown={(e) => onMouseDownResize(e, h)} />
                        ))}
                        <div className="absolute left-1/2 -translate-x-1/2 -top-5 w-4 h-4 bg-amber-500 border border-white rounded-full cursor-grab z-20 flex items-center justify-center" onMouseDown={onMouseDownRotate}>
                          <RotateCw size={10} className="text-white" />
                        </div>
                        <div className="absolute left-1/2 -translate-x-1/2 -top-5 w-0.5 h-4 bg-amber-500 -z-10" />
                      </div>
                    </>
                  )}
                </div>
              );
            })}
            {selectBox && (
              <div
                className="absolute pointer-events-none"
                style={{
                  left: Math.min(selectBox.startX, selectBox.currentX),
                  top: Math.min(selectBox.startY, selectBox.currentY),
                  width: Math.abs(selectBox.currentX - selectBox.startX),
                  height: Math.abs(selectBox.currentY - selectBox.startY),
                  zIndex: 9999,
                  background: 'rgba(59,130,246,0.08)',
                  border: '1px solid rgba(59,130,246,0.5)',
                }}
              />
            )}
          </div>
          <button
            onClick={capture}
            className="py-3 rounded-xl text-sm font-semibold flex items-center justify-center gap-2 transition-all shadow-lg shrink-0"
            style={{
              background: 'rgba(232,172,101,0.15)',
              color: '#e8ac65',
              border: '1px solid rgba(232,172,101,0.25)',
              width: canvasSize.w,
            }}
          >
            Usar como imagen
          </button>
        </div>

        <div className="w-64 bg-gk-card rounded-xl border border-gk-border flex flex-col overflow-hidden shrink-0">
          <div className="px-4 py-3 border-b border-gk-border font-medium text-sm text-gk-text-primary flex items-center justify-between" style={{background: 'rgba(232,172,101,0.15)'}}>
            <span>{selectedEls.length > 1 ? `${selectedEls.length} seleccionados` : 'Propiedades'}</span>
            <div className="flex gap-1">
              <button onClick={undo} className={`p-1.5 rounded-lg transition-colors ${canUndo ? 'v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50' : 'opacity-30 cursor-default'}`} disabled={!canUndo} title="Deshacer"><Undo2 size={14} className="text-gk-text-secondary" /></button>
              <button onClick={redo} className={`p-1.5 rounded-lg transition-colors ${canRedo ? 'v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50' : 'opacity-30 cursor-default'}`} disabled={!canRedo} title="Rehacer"><Redo2 size={14} className="text-gk-text-secondary" /></button>
            </div>
          </div>
          <div className="flex-1 overflow-y-auto px-4 py-3 space-y-3">
            {selectedEls.length === 0 && <div className="text-xs text-gk-text-tertiary text-center py-4">Selecciona un elemento</div>}

            {selectedEls.length > 1 && (
              <>
                <div className="grid grid-cols-2 gap-2">
                  <button onClick={alignHorizontal} className="p-2 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg flex items-center justify-center transition-colors" title="Centrar en eje horizontal (misma altura)"><AlignCenterHorizontal size={16} className="text-gk-text-secondary" /></button>
                  <button onClick={alignVertical} className="p-2 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg flex items-center justify-center transition-colors" title="Centrar en eje vertical (misma posición horizontal)"><AlignCenterVertical size={16} className="text-gk-text-secondary" /></button>
                  <button onClick={distributeHorizontal} className="p-2 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg flex items-center justify-center transition-colors" title="Distribuir horizontalmente"><AlignHorizontalDistributeCenter size={16} className="text-gk-text-secondary" /></button>
                  <button onClick={distributeVertical} className="p-2 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg flex items-center justify-center transition-colors" title="Distribuir verticalmente"><AlignVerticalDistributeCenter size={16} className="text-gk-text-secondary" /></button>
                </div>
                <div className="flex gap-2">
                  <button onClick={bringForward} className="flex-1 p-2 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg transition-colors" title="Traer al frente"><ChevronUp size={14} className="mx-auto text-gk-text-secondary" /></button>
                  <button onClick={sendBackward} className="flex-1 p-2 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg transition-colors" title="Enviar atrás"><ChevronDown size={14} className="mx-auto text-gk-text-secondary" /></button>
                  <button onClick={deleteSelected} className="flex-1 p-2 bg-red-900/30 hover:bg-red-900/50 rounded-lg transition-colors" title="Eliminar"><Trash2 size={14} className="mx-auto text-stat-rose" /></button>
                </div>
              </>
            )}

            {selectedEls.length === 1 && primarySelected && primarySelected.type !== 'field' && (
              <>
                <div className="flex gap-2">
                  <button onClick={bringForward} className="flex-1 p-2 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg transition-colors" title="Traer al frente"><ChevronUp size={14} className="mx-auto text-gk-text-secondary" /></button>
                  <button onClick={sendBackward} className="flex-1 p-2 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg transition-colors" title="Enviar atrás"><ChevronDown size={14} className="mx-auto text-gk-text-secondary" /></button>
                  <button onClick={deleteSelected} className="flex-1 p-2 bg-red-900/30 hover:bg-red-900/50 rounded-lg transition-colors" title="Eliminar"><Trash2 size={14} className="mx-auto text-stat-rose" /></button>
                </div>

                {primarySelected.type !== 'arrow' && primarySelected.type !== 'number' && primarySelected.type !== 'text' && (
                  <div>
                    {primarySelected.src?.includes('/picas/') ? (
                      <>
                        <label className="block text-xs text-gk-text-tertiary mb-1.5">Tamaño {Math.round(primarySelected.w)}×{Math.round(primarySelected.h)}px</label>
                        <input type="range" min="1" max="9" step="1" value={Math.max(1, Math.min(9, Math.round(primarySelected.w)))} onChange={e => { const newW = Number(e.target.value); const ratio = primarySelected.h / primarySelected.w; updateSelected({ w: newW, h: Math.round(newW * ratio) }); }} className="w-full accent-gk-accent" />
                      </>
                    ) : (
                      (() => {
                      const defDim = primarySelected.defaultDim || 120;
                      const minSize = Math.round(defDim * 0.1);
                      const curW = Math.round(primarySelected.w);
                      const maxSize = Math.max(Math.round(defDim * 3), curW);
                      return (
                        <>
                          <label className="block text-xs text-gk-text-tertiary mb-1.5">Tamaño {curW}×{Math.round(primarySelected.h)}px</label>
                          <input type="range" min={minSize} max={maxSize} value={curW} onChange={e => { const newW = Number(e.target.value); const ratio = primarySelected.h / primarySelected.w; updateSelected({ w: newW, h: Math.round(newW * ratio) }); }} className="w-full accent-gk-accent" />
                          <div className="flex justify-between text-[10px] text-gk-text-tertiary mt-0.5">
                            <span>{minSize}px</span>
                            <span>{maxSize}px</span>
                          </div>
                        </>
                      );
                    })()
                    )}
                  </div>
                )}

                <button onClick={duplicateSelected} className="w-full px-3 py-2 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg text-xs text-gk-text-primary flex items-center justify-center gap-2 transition-colors"><Square size={13} /> Duplicar</button>

                {primarySelected.type !== 'arrow' && (
                  <>
                    <div className="pt-2">
                      <label className="block text-xs text-gk-text-tertiary mb-1.5">Rotación ({Math.round(primarySelected.rotation || 0)}°)</label>
                      <input type="range" min="-180" max="180" value={primarySelected.rotation || 0} onChange={e => updateSelected({ rotation: Number(e.target.value) })} className="w-full accent-gk-accent" />
                    </div>
                    {(primarySelected.type === 'object' || primarySelected.type === 'image') && (
                      <div className="flex gap-2">
                        <button onClick={() => updateSelected({ rotation: normalizeRotation((primarySelected.rotation || 0) - 45) })} className="flex-1 px-2 py-1.5 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg text-xs text-gk-text-secondary transition-colors">⟲ -45°</button>
                        <button onClick={() => updateSelected({ rotation: 0 })} className="flex-1 px-2 py-1.5 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg text-xs text-gk-text-secondary transition-colors">0°</button>
                        <button onClick={() => updateSelected({ rotation: normalizeRotation((primarySelected.rotation || 0) + 45) })} className="flex-1 px-2 py-1.5 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg text-xs text-gk-text-secondary transition-colors">⟳ +45°</button>
                      </div>
                    )}
                    <div>
                      <label className="block text-xs text-gk-text-tertiary mb-1.5">Opacidad</label>
                      <input type="range" min="0.1" max="1" step="0.05" value={primarySelected.opacity ?? 1} onChange={e => updateSelected({ opacity: Number(e.target.value) })} className="w-full accent-gk-accent" />
                    </div>
                    {(primarySelected.type === 'object' || primarySelected.type === 'image') && (
                      <div className="flex gap-2">
                        <button onClick={() => updateSelected({ flipH: !primarySelected.flipH })} className={`flex-1 px-3 py-2 rounded-lg text-xs transition-colors ${primarySelected.flipH ? 'v2-btn-active font-semibold' : 'v2-btn-inactive'}`}>
                          ↔ Voltear horizontal
                        </button>
                      </div>
                    )}
                  </>
                )}

                {(primarySelected.type === 'rect' || primarySelected.type === 'circle' || primarySelected.type === 'triangle') && (
                  <>
                    <div>
                      <label className="block text-xs text-gk-text-tertiary mb-1.5">Borde</label>
                      <div className="flex gap-2 items-center">
                        <input type="color" value={primarySelected.stroke} onChange={e => updateSelected({ stroke: e.target.value })} className="w-9 h-9 rounded-lg cursor-pointer shrink-0 border-0 bg-transparent" />
                        <input type="number" min="1" max="20" value={primarySelected.strokeWidth} onChange={e => updateSelected({ strokeWidth: Number(e.target.value) })} className="w-14 px-2 py-1.5 bg-gk-page/50 border border-gk-border/50 rounded-lg text-xs text-gk-text-primary text-center focus:outline-none focus:border-gk-accent/50" />
                        <div className="flex gap-1.5 flex-1">
                          {['solid','dashed'].map(ss => (
                            <button key={ss} onClick={() => updateSelected({ strokeStyle: ss })} className={`flex-1 px-2 py-1.5 rounded-lg text-xs transition-colors ${primarySelected.strokeStyle === ss ? 'v2-btn-active font-semibold' : 'v2-btn-inactive'}`}>{ss === 'solid' ? '─' : '┅'}</button>
                          ))}
                        </div>
                      </div>
                    </div>
                    <div>
                      <label className="block text-xs text-gk-text-tertiary mb-1.5">Relleno</label>
                      <div className="flex gap-1.5 mb-2">
                        {['transparent','solid','striped'].map(ft => (
                          <button key={ft} onClick={() => updateSelected({ fillType: ft })} className={`flex-1 px-2 py-1.5 rounded-lg text-xs transition-colors ${primarySelected.fillType === ft ? 'v2-btn-active font-semibold' : 'v2-btn-inactive'}`}>{ft === 'transparent' ? 'Vacío' : ft === 'solid' ? 'Sólido' : 'Rayado'}</button>
                        ))}
                      </div>
                      {primarySelected.fillType === 'solid' && (
                        <input type="color" value={primarySelected.fill === 'transparent' ? '#000000' : primarySelected.fill} onChange={e => updateSelected({ fill: e.target.value })} className="w-full h-9 rounded-lg cursor-pointer border-0 bg-transparent" />
                      )}
                      {primarySelected.fillType === 'striped' && (
                        <>
                          <input type="color" value={primarySelected.fill === 'transparent' ? primarySelected.stroke : primarySelected.fill} onChange={e => updateSelected({ fill: e.target.value })} className="w-full h-9 rounded-lg cursor-pointer mb-2 border-0 bg-transparent" />
                          <div>
                            <label className="block text-[10px] text-gk-text-tertiary mb-1">Opacidad ({Math.round((primarySelected.fillOpacity ?? 0.2) * 100)}%)</label>
                            <input type="range" min="0.05" max="1" step="0.05" value={primarySelected.fillOpacity ?? 0.2} onChange={e => updateSelected({ fillOpacity: Number(e.target.value) })} className="w-full accent-gk-accent" />
                          </div>
                        </>
                      )}
                    </div>
                  </>
                )}

                {primarySelected.type === 'arrow' && (
                  <>
                    <div className="border-t border-gk-border/50 pt-3 mt-1">
                      <label className="block text-xs text-gk-text-tertiary mb-1.5">Línea</label>
                      <div className="flex gap-2 items-center">
                        <input type="color" value={primarySelected.stroke} onChange={e => updateSelected({ stroke: e.target.value })} className="w-9 h-9 rounded-lg cursor-pointer shrink-0 border-0 bg-transparent" />
                        <input type="number" min="1" max="20" value={primarySelected.strokeWidth} onChange={e => updateSelected({ strokeWidth: Number(e.target.value) })} className="w-14 px-2 py-1.5 bg-gk-page/50 border border-gk-border/50 rounded-lg text-xs text-gk-text-primary text-center focus:outline-none focus:border-gk-accent/50" />
                        <div className="flex gap-1.5 flex-1">
                          {['solid','dashed'].map(ss => (
                            <button key={ss} onClick={() => updateSelected({ strokeStyle: ss })} className={`flex-1 px-2 py-1.5 rounded-lg text-xs transition-colors ${primarySelected.strokeStyle === ss ? 'v2-btn-active font-semibold' : 'v2-btn-inactive'}`}>{ss === 'solid' ? '─' : '┅'}</button>
                          ))}
                        </div>
                      </div>
                    </div>
                    <div>
                      <label className="block text-xs text-gk-text-tertiary mb-1.5">Punta</label>
                      <div className="flex gap-1.5 mb-2">
                        {['standard','round'].map(hs => (
                          <button key={hs} onClick={() => updateSelected({ headStyle: hs })} className={`flex-1 px-2 py-1.5 rounded-lg text-xs transition-colors ${primarySelected.headStyle === hs ? 'v2-btn-active font-semibold' : 'v2-btn-inactive'}`}>{hs === 'standard' ? 'Triangular' : 'Redonda'}</button>
                        ))}
                      </div>
                      <div className="flex items-center gap-2">
                        <button onClick={() => updateSelected({ doubleHead: !primarySelected.doubleHead })} className={`px-2.5 py-1.5 rounded-lg text-xs transition-colors ${primarySelected.doubleHead ? 'v2-btn-active font-semibold' : 'v2-btn-inactive'}`}>{primarySelected.doubleHead ? 'Doble' : 'Simple'}</button>
                        <label className="text-[10px] text-gk-text-tertiary">Tamaño ({primarySelected.headSize || 4})</label>
                      </div>
                      <input type="range" min="1" max="6" value={primarySelected.headSize || 4} onChange={e => updateSelected({ headSize: Number(e.target.value) })} className="w-full mt-1.5 accent-gk-accent" />
                    </div>
                  </>
                )}

                {primarySelected.type === 'text' && (
                  <>
                    <button onClick={() => setEditingTextId(primarySelected.id)} className="w-full px-3 py-2 bg-gk-accent hover:bg-gk-accent rounded-lg text-xs text-white flex items-center justify-center gap-2 transition-colors"><Type size={13} /> Editar texto</button>
                    <div className="flex gap-2 items-center">
                      <label className="text-xs text-gk-text-tertiary shrink-0 w-10">Color</label>
                      <input type="color" value={primarySelected.color} onChange={e => updateSelected({ color: e.target.value })} className="w-9 h-9 rounded-lg cursor-pointer shrink-0 border-0 bg-transparent" />
                      <input type="number" min="8" max="120" value={primarySelected.fontSize} onChange={e => updateSelected({ fontSize: Number(e.target.value) })} className="w-14 px-2 py-1.5 bg-gk-page/50 border border-gk-border/50 rounded-lg text-xs text-gk-text-primary text-center focus:outline-none focus:border-gk-accent/50" />
                      <select value={primarySelected.fontWeight} onChange={e => updateSelected({ fontWeight: e.target.value })} className="flex-1 px-2 py-1.5 bg-gk-page/50 border border-gk-border/50 rounded-lg text-xs text-gk-text-primary focus:outline-none focus:border-gk-accent/50"><option value="normal">Normal</option><option value="bold">Negrita</option></select>
                    </div>
                    <div>
                      <label className="block text-xs text-gk-text-tertiary mb-1.5">Tamaño caja ({Math.round(primarySelected.w)}x{Math.round(primarySelected.h)})</label>
                      <input type="range" min="20" max="300" value={Math.round(primarySelected.w)} onChange={e => { const newW = Number(e.target.value); const ratio = newW / primarySelected.w; updateSelected({ w: newW, h: Math.round(primarySelected.h * ratio) }); }} className="w-full accent-gk-accent" />
                    </div>
                    <div className="flex gap-2 items-center">
                      <label className="text-xs text-gk-text-tertiary shrink-0 w-10">Fondo</label>
                      <input type="color" value={primarySelected.bgColor === 'transparent' ? '#000000' : primarySelected.bgColor} onChange={e => updateSelected({ bgColor: e.target.value })} className="w-9 h-9 rounded-lg cursor-pointer shrink-0 border-0 bg-transparent" />
                      <button onClick={() => updateSelected({ bgColor: 'transparent' })} className={`flex-1 px-3 py-1.5 rounded-lg text-xs transition-colors ${primarySelected.bgColor === 'transparent' ? 'v2-btn-active font-semibold' : 'v2-btn-inactive'}`}>Sin fondo</button>
                    </div>
                    <div className="flex gap-2 items-center">
                      <label className="text-xs text-gk-text-tertiary shrink-0 w-10">Borde</label>
                      <input type="color" value={primarySelected.stroke} onChange={e => updateSelected({ stroke: e.target.value })} className="w-9 h-9 rounded-lg cursor-pointer shrink-0 border-0 bg-transparent" />
                      <input type="number" min="0" max="20" value={primarySelected.strokeWidth} onChange={e => updateSelected({ strokeWidth: Number(e.target.value) })} className="w-14 px-2 py-1.5 bg-gk-page/50 border border-gk-border/50 rounded-lg text-xs text-gk-text-primary text-center focus:outline-none focus:border-gk-accent/50" />
                      <button onClick={() => updateSelected({ noStroke: !primarySelected.noStroke })} className={`flex-1 px-3 py-1.5 rounded-lg text-xs transition-colors ${primarySelected.noStroke ? 'v2-btn-active font-semibold' : 'v2-btn-inactive'}`}>{primarySelected.noStroke ? 'Con borde' : 'Sin borde'}</button>
                    </div>
                    <div>
                      <label className="block text-xs text-gk-text-tertiary mb-1.5">Alineación</label>
                      <div className="flex gap-1.5">
                        {['left','center','right'].map(ta => {
                          const isActive = primarySelected.textAlign === ta || (!primarySelected.textAlign && ta === 'left');
                          return (
                            <button key={ta} onClick={() => updateSelected({ textAlign: ta })} className={`flex-1 px-2 py-2 rounded-lg text-xs transition-colors ${isActive ? 'v2-btn-active font-semibold' : 'v2-btn-inactive'}`}>
                              {ta === 'left' ? <AlignLeft size={14} className="mx-auto" /> : ta === 'center' ? <AlignCenter size={14} className="mx-auto" /> : <AlignRight size={14} className="mx-auto" />}
                            </button>
                          );
                        })}
                      </div>
                    </div>
                  </>
                )}

                {primarySelected.type === 'number' && (
                  <>
                    <div className="flex items-center gap-2">
                      <label className="text-xs text-gk-text-tertiary shrink-0 w-8">Nº</label>
                      <button onClick={() => updateSelected({ number: Math.max(1, (primarySelected.number || 1) - 1) })} className="w-10 h-10 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg text-lg text-gk-text-primary flex items-center justify-center transition-colors">-</button>
                      <input type="number" min="1" value={primarySelected.number || 1} onChange={e => updateSelected({ number: Math.max(1, Number(e.target.value)) })} className="w-14 h-10 px-1 bg-gk-page/50 border border-gk-border/50 rounded-lg text-sm text-gk-text-primary text-center focus:outline-none focus:border-gk-accent/50" />
                      <button onClick={() => updateSelected({ number: (primarySelected.number || 1) + 1 })} className="w-10 h-10 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg text-lg text-gk-text-primary flex items-center justify-center transition-colors">+</button>
                    </div>
                    <div>
                      <label className="block text-xs text-gk-text-tertiary mb-1.5">Tamaño ({Math.round(primarySelected.w)}px)</label>
                      <input type="range" min="20" max="200" value={Math.round(primarySelected.w)} onChange={e => { const newSize = Number(e.target.value); const ratio = newSize / primarySelected.w; updateSelected({ w: newSize, h: newSize, fontSize: Math.round(primarySelected.fontSize * ratio) }); }} className="w-full accent-gk-accent" />
                    </div>
                    <div className="flex gap-2 items-center">
                      <label className="text-xs text-gk-text-tertiary shrink-0 w-14">Color nº</label>
                      <input type="color" value={primarySelected.numberColor} onChange={e => updateSelected({ numberColor: e.target.value })} className="w-9 h-9 rounded-lg cursor-pointer border-0 bg-transparent" />
                    </div>
                    <div className="flex gap-2 items-center">
                      <label className="text-xs text-gk-text-tertiary shrink-0 w-14">Borde</label>
                      <input type="color" value={primarySelected.stroke} onChange={e => updateSelected({ stroke: e.target.value })} className="w-9 h-9 rounded-lg cursor-pointer shrink-0 border-0 bg-transparent" />
                      <input type="number" min="0" max="20" value={primarySelected.strokeWidth} onChange={e => updateSelected({ strokeWidth: Number(e.target.value) })} className="w-14 px-2 py-1.5 bg-gk-page/50 border border-gk-border/50 rounded-lg text-xs text-gk-text-primary text-center focus:outline-none focus:border-gk-accent/50" />
                      <button onClick={() => updateSelected({ noStroke: !primarySelected.noStroke })} className={`flex-1 px-3 py-1.5 rounded-lg text-xs transition-colors ${primarySelected.noStroke ? 'v2-btn-active font-semibold' : 'v2-btn-inactive'}`}>{primarySelected.noStroke ? 'Con borde' : 'Sin borde'}</button>
                    </div>
                    <div className="flex gap-2 items-center">
                      <label className="text-xs text-gk-text-tertiary shrink-0 w-14">Fondo</label>
                      <input type="color" value={primarySelected.bgColor === 'transparent' ? '#ffffff' : primarySelected.bgColor} onChange={e => updateSelected({ bgColor: e.target.value })} className="w-9 h-9 rounded-lg cursor-pointer border-0 bg-transparent" />
                      <button onClick={() => updateSelected({ bgColor: 'transparent' })} className={`flex-1 px-3 py-1.5 rounded-lg text-xs transition-colors ${primarySelected.bgColor === 'transparent' ? 'v2-btn-active font-semibold' : 'v2-btn-inactive'}`}>Sin fondo</button>
                    </div>
                  </>
                )}

                {(primarySelected.type === 'rect' || primarySelected.type === 'circle' || primarySelected.type === 'triangle' || primarySelected.type === 'arrow') && (
                  <div className="border-t border-gk-border/50 pt-3 mt-1">
                    <label className="block text-xs text-gk-text-tertiary mb-2">Presets</label>
                    {showPresetName ? (
                      <div className="flex gap-1.5 mb-2">
                        <input type="text" value={presetName} onChange={e => setPresetName(e.target.value)} placeholder="Nombre" className="flex-1 px-2.5 py-1.5 bg-gk-page/50 border border-gk-border/50 rounded-lg text-xs text-gk-text-primary focus:outline-none focus:border-gk-accent/50" autoFocus onKeyDown={e => { if (e.key === 'Enter') saveShapePreset(); if (e.key === 'Escape') { setShowPresetName(false); setPresetName(''); } }} />
                        <button onClick={saveShapePreset} className="px-2.5 py-1.5 bg-gk-accent hover:bg-gk-accent rounded-lg text-xs text-white transition-colors"><Save size={12} /></button>
                        <button onClick={() => { setShowPresetName(false); setPresetName(''); }} className="px-2.5 py-1.5 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg text-xs text-gk-text-secondary transition-colors">✕</button>
                      </div>
                    ) : (
                      <button onClick={() => setShowPresetName(true)} className="w-full px-3 py-2 mb-2 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg text-xs text-gk-text-primary flex items-center justify-center gap-2 transition-colors"><Star size={12} /> Guardar preset</button>
                    )}
                    {(shapePresets[primarySelected.type] || []).length > 0 && (
                      <div className="space-y-1">
                        {(shapePresets[primarySelected.type] || []).map(p => (
                          <div key={p.id} className="flex items-center gap-1.5">
                            <button onClick={() => loadShapePreset(p)} className="flex-1 px-3 py-2 v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg text-xs text-gk-text-primary text-left transition-colors" title={p.name}>{p.name}</button>
                            <button onClick={() => deleteShapePreset(p.id)} className="shrink-0 w-8 h-8 flex items-center justify-center v2-btn-panel border border-gk-border/30 hover:bg-gk-elevated hover:border-gk-border/50 rounded-lg text-stat-rose hover:text-stat-rose text-xs transition-colors">✕</button>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )}
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
